on:
  pull_request:
    types: [ opened, synchronize ]

  workflow_dispatch:

jobs:

  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

      - name: Install dependencies
        run: pnpm install

      - name: Run eslint
        run: pnpm lint:eslint

  stylelint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

      - name: Install dependencies
        run: pnpm install

      - name: Run stylelint
        run: pnpm lint:stylelint

  prettier:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      - name: Install pnpm
        run: curl -f https://get.pnpm.io/v6.14.js | node - add --global pnpm@6

      - name: Install dependencies
        run: pnpm install

      - name: Run prettier
        run: pnpm lint:prettier

